// <auto-generated />
using System;
using FoodShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodShop.Data.Migrations
{
    [DbContext(typeof(FoodShopDbContext))]
    [Migration("20260524140205_AddIngredientPreptimeAndCalories")]
    partial class AddIngredientPreptimeAndCalories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FoodShop.Data.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FoodShop.Data.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DateBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("longtext");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("JobId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Address = "Phnom Penh",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateBirth = new DateOnly(1998, 1, 1),
                            Email = "finn@foodshop.com",
                            EmployeeName = "F1nnTh3Human",
                            JobId = 1,
                            Password = "Finn123",
                            Phone = "012345678",
                            Remark = "Main administrator account",
                            RoleId = 1
                        },
                        new
                        {
                            EmployeeID = 2,
                            Address = "Kandal",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateBirth = new DateOnly(1997, 5, 12),
                            Email = "jake@foodshop.com",
                            EmployeeName = "Jake",
                            JobId = 2,
                            Password = "Jake123",
                            Phone = "098765432",
                            Remark = "Store manager",
                            RoleId = 2
                        },
                        new
                        {
                            EmployeeID = 3,
                            Address = "Takeo",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateBirth = new DateOnly(1999, 8, 20),
                            Email = "marceline@foodshop.com",
                            EmployeeName = "Marceline",
                            JobId = 3,
                            Password = "Marceline123",
                            Phone = "097111222",
                            Remark = "Morning seller",
                            RoleId = 3
                        },
                        new
                        {
                            EmployeeID = 4,
                            Address = "Battambang",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateBirth = new DateOnly(1996, 3, 15),
                            Email = "iceking@foodshop.com",
                            EmployeeName = "IceKing",
                            JobId = 3,
                            Password = "Iceking123",
                            Phone = "096333444",
                            Remark = "Afternoon seller",
                            RoleId = 3
                        },
                        new
                        {
                            EmployeeID = 5,
                            Address = "Siem Reap",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateBirth = new DateOnly(2001, 11, 11),
                            Email = "gumball@foodshop.com",
                            EmployeeName = "Gumball",
                            JobId = 2,
                            Password = "Gumball123",
                            Phone = "088555666",
                            Remark = "Night seller",
                            RoleId = 3
                        },
                        new
                        {
                            EmployeeID = 6,
                            Address = "Siem Reap",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateBirth = new DateOnly(2001, 11, 11),
                            Email = "darwin@foodshop.com",
                            EmployeeName = "Gumball",
                            JobId = 4,
                            Password = "Darwin123",
                            Phone = "086555666",
                            Remark = "Night seller",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("FoodShop.Data.Food_Categories", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("longtext");

                    b.HasKey("CategoryID");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Fast Food",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Burgers, pizza, fried chicken, and snacks"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Drink",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Drinks like coffee, tea, and soft drinks"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Desserts",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sweet foods like cakes and ice cream"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Snacks",
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Light snacks and side dishes"
                        });
                });

            modelBuilder.Entity("FoodShop.Data.Foods", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<string>("Calories")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FoodCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("FoodImageID")
                        .HasColumnType("longtext");

                    b.Property<string>("FoodName")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredients")
                        .HasColumnType("longtext");

                    b.Property<string>("PrepTime")
                        .HasColumnType("longtext");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("FoodID");

                    b.HasIndex("FoodCategoryID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Grilled chicken burger with fresh vegetables",
                            FoodCategoryID = 1,
                            FoodImageID = "burger.jpg",
                            FoodName = "Chicken Burger",
                            Qty = 50,
                            SellPrice = 3.50m
                        },
                        new
                        {
                            FoodID = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic cheese pizza with mozzarella",
                            FoodCategoryID = 1,
                            FoodImageID = "pizza.jpg",
                            FoodName = "Cheese Pizza",
                            Qty = 40,
                            SellPrice = 5.00m
                        },
                        new
                        {
                            FoodID = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crispy fried chicken",
                            FoodCategoryID = 1,
                            FoodImageID = "grilled chicken.jpg",
                            FoodName = "Chicken",
                            Qty = 60,
                            SellPrice = 4.00m
                        },
                        new
                        {
                            FoodID = 4,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cold brewed iced coffee",
                            FoodCategoryID = 2,
                            FoodImageID = "iced_coffee.jpg",
                            FoodName = "Iced Coffee",
                            Qty = 100,
                            SellPrice = 1.50m
                        },
                        new
                        {
                            FoodID = 5,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweet milk tea with pearls",
                            FoodCategoryID = 2,
                            FoodImageID = "milk_tea.jpg",
                            FoodName = "Milk Tea",
                            Qty = 80,
                            SellPrice = 2.00m
                        },
                        new
                        {
                            FoodID = 6,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Golden crispy french fries",
                            FoodCategoryID = 1,
                            FoodImageID = "fries.jpg",
                            FoodName = "French Fries",
                            Qty = 70,
                            SellPrice = 2.50m
                        });
                });

            modelBuilder.Entity("FoodShop.Data.Invoice_Details", b =>
                {
                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("InvoiceID", "FoodID");

                    b.HasIndex("FoodID");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("FoodShop.Data.Invoices", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SellerID")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("DeliveryID");

                    b.HasIndex("SellerID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FoodShop.Data.Jobs", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JobID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("JobName")
                        .HasColumnType("longtext");

                    b.HasKey("JobID");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobID = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage the whole system",
                            JobName = "Admin"
                        },
                        new
                        {
                            JobID = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Handle customer payments and invoices",
                            JobName = "Cashier"
                        },
                        new
                        {
                            JobID = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Assist customers and handle complaints",
                            JobName = "Customer Support"
                        },
                        new
                        {
                            JobID = 4,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Assist customers and Delivered ordered",
                            JobName = "Delivery"
                        });
                });

            modelBuilder.Entity("FoodShop.Data.Pages", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PageID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("longtext");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext");

                    b.HasKey("PageID");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            PageID = 1,
                            CreatedAt = new DateTime(2026, 3, 17, 4, 20, 13, 0, DateTimeKind.Unspecified),
                            Descriptions = "System dashboard",
                            PageName = "Dashboard"
                        },
                        new
                        {
                            PageID = 2,
                            CreatedAt = new DateTime(2026, 3, 17, 4, 20, 18, 0, DateTimeKind.Unspecified),
                            Descriptions = "Manage food categories",
                            PageName = "Category"
                        },
                        new
                        {
                            PageID = 3,
                            CreatedAt = new DateTime(2026, 3, 17, 4, 20, 22, 0, DateTimeKind.Unspecified),
                            Descriptions = "Manage food products",
                            PageName = "Food"
                        },
                        new
                        {
                            PageID = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 6, 58, 0, DateTimeKind.Unspecified),
                            Descriptions = "Manage customers",
                            PageName = "Customer"
                        },
                        new
                        {
                            PageID = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 7, 5, 0, DateTimeKind.Unspecified),
                            Descriptions = "Manage employees",
                            PageName = "Employee"
                        },
                        new
                        {
                            PageID = 6,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 7, 10, 0, DateTimeKind.Unspecified),
                            Descriptions = "Manage jobs",
                            PageName = "Job"
                        },
                        new
                        {
                            PageID = 7,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 7, 18, 0, DateTimeKind.Unspecified),
                            Descriptions = "Manage roles and permissions",
                            PageName = "Role"
                        },
                        new
                        {
                            PageID = 8,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 7, 22, 0, DateTimeKind.Unspecified),
                            Descriptions = "Manage application pages",
                            PageName = "Page"
                        },
                        new
                        {
                            PageID = 9,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 7, 22, 0, DateTimeKind.Unspecified),
                            Descriptions = "Manage delivered pages",
                            PageName = "Delivery"
                        });
                });

            modelBuilder.Entity("FoodShop.Data.Role_Permissions", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.HasKey("RoleID", "PageID");

                    b.HasIndex("PageID");

                    b.ToTable("Role_Permissions");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            PageID = 1
                        },
                        new
                        {
                            RoleID = 2,
                            PageID = 1
                        },
                        new
                        {
                            RoleID = 3,
                            PageID = 1
                        },
                        new
                        {
                            RoleID = 1,
                            PageID = 2
                        },
                        new
                        {
                            RoleID = 2,
                            PageID = 2
                        },
                        new
                        {
                            RoleID = 1,
                            PageID = 3
                        },
                        new
                        {
                            RoleID = 2,
                            PageID = 3
                        },
                        new
                        {
                            RoleID = 3,
                            PageID = 3
                        },
                        new
                        {
                            RoleID = 1,
                            PageID = 4
                        },
                        new
                        {
                            RoleID = 2,
                            PageID = 4
                        },
                        new
                        {
                            RoleID = 3,
                            PageID = 4
                        },
                        new
                        {
                            RoleID = 1,
                            PageID = 5
                        },
                        new
                        {
                            RoleID = 2,
                            PageID = 5
                        },
                        new
                        {
                            RoleID = 1,
                            PageID = 6
                        },
                        new
                        {
                            RoleID = 2,
                            PageID = 6
                        },
                        new
                        {
                            RoleID = 1,
                            PageID = 7
                        },
                        new
                        {
                            RoleID = 1,
                            PageID = 8
                        });
                });

            modelBuilder.Entity("FoodShop.Data.Roles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<int?>("ByEmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleID");

                    b.HasIndex("ByEmployeeID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 6, 2, 4, 868, DateTimeKind.Local).AddTicks(2090),
                            Descriptions = "System administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            CreatedAt = new DateTime(2026, 5, 24, 6, 2, 4, 868, DateTimeKind.Local).AddTicks(2095),
                            Descriptions = "Manage orders and employees",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleID = 3,
                            CreatedAt = new DateTime(2026, 5, 24, 6, 2, 4, 868, DateTimeKind.Local).AddTicks(2099),
                            Descriptions = "Limited employee access",
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("FoodShop.Data.Employee", b =>
                {
                    b.HasOne("FoodShop.Data.Jobs", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodShop.Data.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FoodShop.Data.Foods", b =>
                {
                    b.HasOne("FoodShop.Data.Food_Categories", "FoodCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodCategory");
                });

            modelBuilder.Entity("FoodShop.Data.Invoice_Details", b =>
                {
                    b.HasOne("FoodShop.Data.Foods", "Foods")
                        .WithMany("Invoice_Details")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodShop.Data.Invoices", "Invoices")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foods");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("FoodShop.Data.Invoices", b =>
                {
                    b.HasOne("FoodShop.Data.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodShop.Data.Employee", "Delivery")
                        .WithMany("DeliveredInvoices")
                        .HasForeignKey("DeliveryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodShop.Data.Employee", "Seller")
                        .WithMany("Invoices")
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Delivery");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("FoodShop.Data.Role_Permissions", b =>
                {
                    b.HasOne("FoodShop.Data.Pages", "Pages")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodShop.Data.Roles", "Roles")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pages");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("FoodShop.Data.Roles", b =>
                {
                    b.HasOne("FoodShop.Data.Employee", "ByEmployee")
                        .WithMany()
                        .HasForeignKey("ByEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ByEmployee");
                });

            modelBuilder.Entity("FoodShop.Data.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("FoodShop.Data.Employee", b =>
                {
                    b.Navigation("DeliveredInvoices");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("FoodShop.Data.Food_Categories", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("FoodShop.Data.Foods", b =>
                {
                    b.Navigation("Invoice_Details");
                });

            modelBuilder.Entity("FoodShop.Data.Invoices", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("FoodShop.Data.Pages", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FoodShop.Data.Roles", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
